esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "AiOHotspot"
    password: "SmartHome2025"

captive_portal:

mdns:
  disabled: false

i2c:
  sda: GPIO0
  scl: GPIO1
  frequency: 15khz
  scan: false

uart:
  - id: zigbee
    rx_pin: GPIO2
    tx_pin: GPIO3
    baud_rate: 460800
  - id: presence
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 115200
    parity: NONE
    stop_bits: 1

ld2412:
  id: ld2412_radar
  uart_id: presence

bme68x_bsec2_i2c:
  address: 0x76
  model: bme688
  operating_age: 28d
  supply_voltage: 3.3V
  sample_rate: LP
  state_save_interval: 6h
  temperature_offset: 35

esp32_ble_tracker:
  scan_parameters:
    interval: 500ms
    window: 250ms
    active: true

bluetooth_proxy:
  active: true

api:
  encryption:

ota:
  - platform: esphome

web_server:
  port: 80

logger:

